### ISSUE TITLE
Technical Issues

### ISSUE THREAD

**Issue by lexifortune** [Asethi01/Project#3]
Here are some technical issues:
1. The navigation bar is oddly placed and off-center so I think that should be adjusted or expanded upon so that it is not completely empty on one entire side. 
2. I think it would be cool if you maybe integrated some links, especially on the "Recent Race Highlights" page, to other websites that contain more info on the actual races themselves. I know you have a lot of races listed, but maybe just include links to specific websites that provide more information on all of the races, or focus on the ones that are coming up sooner and include links for those specific races on the upcoming dates.

**Comment by Asethi01** [comment]
Hi, I have taken your feedback well and have fixed all that I could find that was not working. I hope you like the website now.
