### ISSUE TITLE
Peer feedback

### ISSUE THREAD

**Issue by faijachoudhury01** [Asethi01/Project#4]
It's really cool that you are doing your website in F1. 

Technical suggestion:
* having a highlight on the menu bar will be helpful for users to know which page they are in
* the color scheme for the text makes it harder to read as the background is brighter. 

content suggestion:
*It would be really nice if you can add something about the famous racers or the cars they have used.
* with the race schedule it would be fun to know who is racing and the details about the race

**Comment by Asethi01** [comment]
Hi, thank you for your feedback. I have made a few changes, I hope it is better now.
